version: "3"

services:
  mc.kairoscraft.net:
    image: minecraftservers/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: always
    deploy:
     resources:
       limits:
         memory: 1.5G
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
